CREATE SEQUENCE CUSTOMER_SEQ_TJA31_GROUP_D
START WITH 100000000
INCREMENT BY 10

drop sequence CUSTOMER_SEQ_TJA31_GROUP_D

CREATE TABLE CUSTOMER_TJA31_GROUP_D(
SSN NUMBER(9) NOT NULL UNIQUE,
CUSTOMER_ID NUMBER(9),
NAME VARCHAR2(20) NOT NULL,
ADDRESS VARCHAR2(100),
AGE NUMBER(3),
PRIMARY KEY(CUSTOMER_ID) 
)
 drop table CUSTOMER_TJA31_GROUP_D
 
select*from CUSTOMER_TJA31_GROUP_D;
delete from CUSTOMER_TJA31_GROUP_D where ssn=123456987
CREATE SEQUENCE ACCOUNT_SEQ_TJA31_GROUP_D
START WITH 200000000
INCREMENT BY 1

drop sequence ACCOUNT_SEQ_TJA31_GROUP_D

CREATE TABLE ACCOUNT_TJA31_GROUP_D(
CUSTOMER_ID NUMBER(9) NOT NULL,
ACCOUNT_ID NUMBER(9) NOT NULL PRIMARY KEY,
ACCOUNT_TYPE VARCHAR2(1) CHECK(ACCOUNT_TYPE = 'S' OR ACCOUNT_TYPE = 'C') NOT NULL,
ACCOUNT_BALANCE NUMBER(10) NOT NULL,
ACCOUNT_CR_DATE DATE NOT NULL,
ACCOUNT_CR_LAST_DATE DATE NOT NULL,
ACCOUNT_DURATION NUMBER NOT NULL,
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_TJA31_GROUP_D(CUSTOMER_ID)
)

 drop table ACCOUNT_TJA31_GROUP_D
select * from ACCOUNT_TJA31_GROUP_D;
CREATE TABLE TRANSACTIONS_TJA31_GROUP_D(
CUSTOMER_ID NUMBER(9) NOT NULL,
ACCOUNT_ID NUMBER(9) NOT NULL,
ACCOUNT_TYPE VARCHAR2(1) CHECK(ACCOUNT_TYPE = 'S' OR ACCOUNT_TYPE = 'C') NOT NULL,
AMOUNT NUMBER(10) NOT NULL,
TRANSACTION_DATE DATE NOT NULL,
SOURCE_ACCOUNT_TYPE VARCHAR2(1) CHECK(SOURCE_ACCOUNT_TYPE = 'S' OR SOURCE_ACCOUNT_TYPE = 'C') NOT NULL,
TARGET_ACCOUNT_TYPE VARCHAR2(1) CHECK(TARGET_ACCOUNT_TYPE = 'S' OR TARGET_ACCOUNT_TYPE = 'C') NOT NULL,
TRANSACTION_DESCRIPTION VARCHAR(25),
TRANSACTION_TYPE VARCHAR(30)CHECK(TRANSACTION_TYPE='DEBIT' OR TRANSACTION_TYPE='CREDIT'),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_TJA31_GROUP_D(CUSTOMER_ID),
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT_TJA31_GROUP_D(ACCOUNT_ID)

)

drop table TRANSACTIONS_TJA31_GROUP_D


CREATE TABLE ACCOUNT_STATUS_TJA31_GROUP_D(
CUSTOMER_ID NUMBER(9) NOT NULL,
ACCOUNT_ID NUMBER(9) NOT NULL,
ACCOUNT_TYPE VARCHAR2(1) CHECK(ACCOUNT_TYPE = 'S' OR ACCOUNT_TYPE = 'C') NOT NULL,
STATUS VARCHAR2(20) NOT NULL,
MESSAGE VARCHAR2(40) NOT NULL,
LAST_UPDATED DATE NOT NULL

)


CREATE TABLE CUSTOMER_STATUS_TJA31_GROUP_D(
SSN_ID NUMBER(9) NOT NULL,
CUSTOMER_ID NUMBER(9) NOT NULL,
STATUS VARCHAR2(20) NOT NULL,
MESSAGE VARCHAR2(40) NOT NULL,
LAST_UPDATED DATE NOT NULL

)


CREATE TABLE USERSTORE_TJA31_GROUP_D(
USERNAME VARCHAR2(20) PRIMARY KEY,
PASSWORD VARCHAR2(20),
TIME_STAMP TIMESTAMP
)

INSERT INTO USERSTORE_TJA31_GROUP_D values('123456789','executive@123',null);
INSERT INTO USERSTORE_TJA31_GROUP_D values('212345678','cashier@123',null);

select * from CUSTOMER_STATUS_TJA31_GROUP_D
select * from ACCOUNT_TJA31_GROUP_D
select * from USERSTORE_TJA31_GROUP_D
select *from CUSTOMER_TJA31_GROUP_D
select *from ACCOUNT_STATUS_TJA31_GROUP_D
select *from TRANSACTIONS_TJA31_GROUP_D
drop table userstore_tja31_group_d;
select SSN from CUSTOMER_TJA31_GROUP_D
select *from CUSTOMER_TJA31_GROUP_D

drop table TRANSACTIONS_TJA31_GROUP_D
drop table CUSTOMER_STATUS_TJA31_GROUP_D
drop table ACCOUNT_STATUS_TJA31_GROUP_D

delete from CUSTOMER_TJA31_GROUP_D where ssn=147852369;


select * from ACCOUNT_TJA31_GROUP_D where CUSTOMER_ID=100000040

delete from CUSTOMER_TJA31_GROUP_D where CUSTOMER_ID=100000030


update ACCOUNT_TJA31_GROUP_D set ACCOUNT_BALANCE=? where ACCOUNT_ID=?
update ACCOUNT_STATUS_TJA31_GROUP_D set STATUS='deleted' MESSAGE='done' where ACCOUNT_ID=200000032



select * from CUSTOMER_TJA31_GROUP_D where CUSTOMER_ID=121212121 or SSN=121212121




select TRANSACTION_DATE,TRANSACTION_DESCRIPTION,TRANSACTION_TYPE,AMOUNT from TRANSACTIONS_TJA31_GROUP_D where ACCOUNT_ID=200000001 AND TRANSACTION_DATE>=TO_DATE('2018-08-20','YYYY-MM-DD') AND TRANSACTION_DATE<=TO_DATE('2018-08-27','YYYY-MM-DD')